[build]
  command = "bun run build"
  publish = "out"

[[redirects]]
  from = "/place"
  to = "https://place-asny23.vercel.app/place"
  status = 200
[[redirects]]
  from = "/place/*"
  to = "https://place-asny23.vercel.app/place/:splat"
  status = 200
