[build.environment]
  NODE_VERSION = "16.15.0"
  NPM_VERSION = "8.10.0"

[[redirects]]
  from = "/place"
  to = "https://place-asny23hub.vercel.app/place"
  status = 200
[[redirects]]
  from = "/place/*"
  to = "https://place-asny23hub.vercel.app/place/:splat"
  status = 200
